In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [2]:
titanic_data=pd.read_csv(r'C:\Users\user\Downloads\titanic_dataset.csv')

In [3]:
titanic_data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
titanic_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


### Preprocessing

In [5]:
titanic_data.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [6]:
for i in ['Age']:
    titanic_data[i]=titanic_data[i].fillna(titanic_data[i].median())

In [7]:
titanic_data.Embarked.fillna(titanic_data.Embarked.mode()[0], inplace = True)

In [8]:
titanic_data.drop(['Cabin'],axis=1,inplace=True)
#dropping cabin column as there is a huge number of null columns

In [9]:
titanic_data.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [10]:
titanic_data.drop(['Name'],axis=1,inplace=True)

In [11]:
titanic_data.Ticket.nunique()

681

In [12]:
titanic_data.drop(['Ticket'],axis=1,inplace=True)

In [13]:
titanic_data.head()

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0            1         0       3    male  22.0      1      0   7.2500        S
1            2         1       1  female  38.0      1      0  71.2833        C
2            3         1       3  female  26.0      0      0   7.9250        S
3            4         1       1  female  35.0      1      0  53.1000        S
4            5         0       3    male  35.0      0      0   8.0500        S

In [14]:
titanic_data1=pd.get_dummies(titanic_data)

In [15]:
titanic_data1.head()

PassengerId  Survived  Pclass   Age  SibSp  Parch     Fare  Sex_female  \
0            1         0       3  22.0      1      0   7.2500           0   
1            2         1       1  38.0      1      0  71.2833           1   
2            3         1       3  26.0      0      0   7.9250           1   
3            4         1       1  35.0      1      0  53.1000           1   
4            5         0       3  35.0      0      0   8.0500           0   

   Sex_male  Embarked_C  Embarked_Q  Embarked_S  
0         1           0           0           1  
1         0           1           0           0  
2         0           0           0           1  
3         0           0           0           1  
4         1           0           0           1

In [16]:
X=titanic_data1.drop(['Survived'],axis=1)
Y=titanic_data1.Survived

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.25,random_state=42)

### Knn model

In [19]:
from sklearn.neighbors import KNeighborsClassifier

In [20]:
knn_model=KNeighborsClassifier()
knn_model=knn_model.fit(X_train,Y_train)

In [21]:
knn_score=knn_model.score(X_test,Y_test)

In [22]:
knn_score

0.6547085201793722

### SVM

In [24]:
from sklearn.svm import SVC


In [25]:
svm_model=SVC()

In [26]:
svm_model=svm_model.fit(X_train,Y_train)

In [27]:
svm_score=svm_model.score(X_test,Y_test)
svm_score

0.6188340807174888

### K-fold cross validation

In [23]:
from sklearn.model_selection import KFold

In [28]:
kfold_validator=KFold(10)

In [31]:
for train_index,test_index in kfold_validator.split(X,Y):
    print('Training index',train_index)
    print('Test Index',test_index)

Training index [ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251
 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269
 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287
 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305
 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323
 324 325 326 327 328 329 330 331 332

In [37]:
from sklearn.model_selection import cross_val_score
cv_result_knn=cross_val_score(knn_model,X,Y,cv=kfold_validator)

In [38]:
cv_result_knn

array([0.56666667, 0.53932584, 0.49438202, 0.57303371, 0.48314607,
       0.56179775, 0.71910112, 0.71910112, 0.68539326, 0.68539326])

In [39]:
cv_result_svm=cross_val_score(svm_model,X,Y,cv=kfold_validator)
cv_result_svm

array([0.56666667, 0.76404494, 0.62921348, 0.5505618 , 0.61797753,
       0.6741573 , 0.58426966, 0.69662921, 0.73033708, 0.65168539])

In [40]:
np.mean(cv_result_knn)

0.6027340823970038

In [41]:
np.mean(cv_result_svm)

0.6465543071161048

### Stratified K-fold cross validation

In [42]:
from sklearn.model_selection import StratifiedKFold

In [44]:
skfold_validator=StratifiedKFold(n_splits=10)

In [45]:
for train_index,test_index in skfold_validator.split(X,Y):
    print('Training index',train_index)
    print('Test Index',test_index)

Training index [ 82  84  85  88  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251
 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269
 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287
 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305
 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323
 324 325 326 327 328 329 330 331 332

In [46]:
scv_result_knn=cross_val_score(knn_model,X,Y,cv=skfold_validator)

In [47]:
scv_result_knn

array([0.45555556, 0.61797753, 0.42696629, 0.4494382 , 0.46067416,
       0.49438202, 0.46067416, 0.47191011, 0.53932584, 0.66292135])

In [48]:
np.mean(scv_result_knn)

0.5039825218476903